#Very simple makefile, supports make all, make clean, and individual makes for each program

all: prolific generation explorer slug slugrace

clean:
	rm -f *.o
	rm -f prolific
	rm -f explorer
	rm -f generation
	rm -f slug
	rm -f slugrace