goatmalloc: goatmalloc.c test_goatmalloc.c
	gcc -o goatmalloc goatmalloc.c test_goatmalloc.c 

# all: goatmalloc.c goatmalloc.h
# 	gcc -o goatmalloc goatmalloc.c 

clean: 
	rm -f *.o
	rm -f goatmalloc