scheduler: test_goatmalloc.c goatmalloc.h
	gcc -o test_goatmalloc test_goatmalloc.c 

all: test_goatmalloc.c goatmalloc.h
	gcc -o test_goatmalloc test_goatmalloc.c 

clean: 
	rm -f *.o
	rm -f scheduler